server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
           - Path=/student/**
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/book/**

  config:
    import: configserver:http://localhost:7000
